# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a6b536f2d6e0c405c1e8948aefe93da33b5691fa8cd614887db023cfe7dc67fe7e92ffcf271c22bf7e37e9a2c37a6e42c5712165e40a3eecabf722d09077608

test:
  secret_key_base: 953985569ae3a34cfb797e11bb322ee719f93fd2665472c50593a9f037a0a048ebe175308a9e860aad2bfc41a874bcc6bc8b41a2b6d3cefe89e6877a0ba19dea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
